{"name": "Login Sem sucesso -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"C:\\Users\\dluca\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dluca\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Create.py\", line 7, in step_impl\n    Create(context).navigate_to()\n  File \"D:\\Devlopment\\aspdotnetcore\\BookListRazor\\teste\\BehaveProject\\features\\pages\\BasePage.py\", line 17, in navigate_to\n    self.context.browser.get(self.url)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Dado que esteja na página create", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=88.0.4324.182)\n\n", "trace": "  File \"C:\\Users\\dluca\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\dluca\\AppData\\Roaming\\Python\\Python39\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Create.py\", line 7, in step_impl\n    Create(context).navigate_to()\n  File \"D:\\Devlopment\\aspdotnetcore\\BookListRazor\\teste\\BehaveProject\\features\\pages\\BasePage.py\", line 17, in navigate_to\n    self.context.browser.get(self.url)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614103996098, "stop": 1614104005222}, {"name": "Quando insiro empty no campo name do create", "status": "skipped", "start": 1614104005240, "stop": 1614104005240}, {"name": "E insiro dev@123 no campo author do create", "status": "skipped", "start": 1614104005240, "stop": 1614104005240}, {"name": "E insiro 5135115313 no campo isbn do create", "status": "skipped", "start": 1614104005240, "stop": 1614104005240}, {"name": "E clico no botão create do create", "status": "skipped", "start": 1614104005240, "stop": 1614104005240}, {"name": "Então verifico que obtive o resultado The Name field is required.", "status": "skipped", "start": 1614104005240, "stop": 1614104005240}], "parameters": [{"name": "nome", "value": "empty"}, {"name": "autor", "value": "dev@123"}, {"name": "isbn", "value": "5135115313"}, {"name": "resultadoEsp", "value": "The Name field is required."}], "start": 1614103996060, "stop": 1614104005240, "uuid": "748d6aba-f00c-4c51-a214-e0b76435ff56", "historyId": "1750d3b122a5548dabc7edf412efc4a3", "fullName": "Create livro em CRUD BookListRazor: Login Sem sucesso", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "TC0000_xx"}, {"name": "tag", "value": "all"}, {"name": "tag", "value": "create"}, {"name": "tag", "value": "createfalha"}, {"name": "tag", "value": "sprint9"}, {"name": "feature", "value": "Create livro em CRUD BookListRazor"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}